spring:
  datasource:
    username: root
    password: 123
    url: jdbc:mysql://127.0.0.1:3306/shixun?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=CTT&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
mybatis:
  mapper-locations: classpath:cn/dsh/shixun/dao/*.xml
  type-aliases-package: cn.dsh.shixun.entity